sudo: false

language: android

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/3.2.1
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/jars-2
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -d -in app/google-services.json.cipher -out app/google-services.json -k $ANDROID_KEY
  - openssl aes-256-cbc -d -in key-store.jks.cipher -out key-store.jks -k $ANDROID_KEY

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./gradlew -i testDebugUnitTest
  - ./gradlew assembleRelease
